Update  jacoco, checkstyle, and sonarcloud

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI/CD Pipeline
 
 on:
   push:
@@ -6,13 +6,24 @@ on:
   pull_request:
     branches: [ "staging", "main" ]
 
+permissions:
+  contents: read
+  pull-requests: read
+
 jobs:
-  build-test:
+  build-test-lint-sonar:
     runs-on: ubuntu-latest
+
+    env:
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      SONAR_PROJECT_KEY: ${{ vars.SONAR_PROJECT_KEY }}
+      SONAR_ORGANIZATION: ${{ vars.SONAR_ORGANIZATION }}
 
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
 
       - name: Setup Java 21
         uses: actions/setup-java@v4
@@ -21,20 +32,34 @@ jobs:
           java-version: "21"
           cache: gradle
 
-      - name: Make gradlew executable
+      - name: Grant execute permission
         run: chmod +x ./gradlew
 
-      # - name: Run Checkstyle
-      #   run: ./gradlew checkstyleMain checkstyleTest
+      - name: Validate SonarCloud config
+        run: |
+          test -n "$SONAR_TOKEN" || (echo "Missing SONAR_TOKEN" && exit 1)
+          test -n "$SONAR_PROJECT_KEY" || (echo "Missing SONAR_PROJECT_KEY" && exit 1)
+          test -n "$SONAR_ORGANIZATION" || (echo "Missing SONAR_ORGANIZATION" && exit 1)
 
-      - name: Run Test
-        run: ./gradlew test
+      - name: Build + Check + Coverage
+        run: ./gradlew --no-daemon clean check jacocoTestReport
 
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarqube-scan-action@v6
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+            -Dsonar.host.url=https://sonarcloud.io
+            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
+            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
+            -Dsonar.sources=src/main
+            -Dsonar.tests=src/test
+            -Dsonar.java.binaries=build/classes
+            -Dsonar.junit.reportPaths=build/test-results/test
+            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
 
-      - name: Build
-        run: ./gradlew build
-
-      # Dummy CD
       - name: Deploy to Staging
         if: github.ref == 'refs/heads/staging'
         run: echo "Deploying to STAGING..."
